In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from PIL import Image
import glob
import torch

/home/shah/miniconda3/envs/selenium_project/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
img_df = pd.read_json("data/cleaned_tabular.json")

In [3]:
img_df.drop(['id','product_name','product_description','category','location','geo_location','longiude_latitude'],axis=1, inplace=True)

In [4]:
img_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7010 entries, 1 to 8090
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   price          7010 non-null   float64
 1   main_category  7010 non-null   object 
dtypes: float64(1), object(1)
memory usage: 164.3+ KB


In [5]:
img_df.head()

price main_category
1    5.0   home_garden
2   20.0   home_garden
3   20.0   home_garden
4  115.0   home_garden
5  450.0   home_garden

In [6]:
labels = img_df['main_category'].astype('category').cat.categories.tolist()
replace_text = {'main_category': {k: v for k,v in zip(labels,list(range(1,len(labels)+1)))}}

In [7]:
img_df = img_df.copy()
img_df.replace(replace_text, inplace=True)
img_df.head()


price  main_category
1    5.0              7
2   20.0              7
3   20.0              7
4  115.0              7
5  450.0              7

In [8]:
img_df['main_category'].dtypes

dtype('int64')

In [9]:
img_df

price  main_category
1       5.0              7
2      20.0              7
3      20.0              7
4     115.0              7
5     450.0              7
...     ...            ...
8085  260.0             13
8086  235.0             13
8088  250.0             13
8089   30.0             13
8090  450.0             13

[7010 rows x 2 columns]

In [15]:
#get images and cast to pytorch tensor and flatten images
#Size already at 128 
from torchvision.transforms import ToTensor
list_img = glob.glob('data/new_images/*.jpg')
for img in list_img:
    images = Image.open(img)
    images = ToTensor()(images)
    images = torch.flatten(images)
    print(images.shape)
    print(images.numpy())

torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[1. 1. 1. ... 1. 1. 1.]
torch.Size([49152])
[0. 0. 0. ... 0. 0. 0.]
torch.Size([49152])
[0. 0. 0. ..

[0.6392157  0.6392157  0.6392157  ... 0.25882354 0.25882354 0.25882354]


In [ ]:
#merge the np array data to the dataframe with categories


